const rows = [
  {
    id: 1143155,
    product: 'Acer Nitro 5',
    img: 'https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg',
    customer: 'Lucas Madrid',
    date: '1 March',
    price: 785,
    mode: 'Cash on Delivery',
    status: 'Approved',
  },
  {
    id: 2235235,
    product: 'Playstation 5',
    img: 'https://m.media-amazon.com/images/I/31JaiPXYI8L._AC_UY327_FMwebp_QL65_.jpg',
    customer: 'Micheal Bae',
    date: '1 March',
    price: 699,
    mode: 'Online Payment',
    status: 'Pending',
  },
  {
    id: 2342353,
    product: 'Redragon S101',
    img: 'https://m.media-amazon.com/images/I/71kr3WAj1FL._AC_UY327_FMwebp_QL65_.jpg',
    customer: 'Shelly Bundie',
    date: '1 March',
    price: 50,
    mode: 'Cash on Delivery',
    status: 'Pending',
  },
  {
    id: 2357741,
    product: 'Razer Blade 15',
    img: 'https://m.media-amazon.com/images/I/71wF7YDIQkL._AC_UY327_FMwebp_QL65_.jpg',
    customer: 'Victor Hawzer Jr.',
    date: '1 March',
    price: 870,
    mode: 'Online',
    status: 'Approved',
  },
  {
    id: 2342355,
    product: 'ASUS ROG Strix',
    img: 'https://m.media-amazon.com/images/I/81hH5vK-MCL._AC_UY327_FMwebp_QL65_.jpg',
    customer: 'Cammy Carol',
    date: '1 March',
    price: 2400,
    mode: 'Online',
    status: 'Pending',
  },
];

export default rows;
